services:
  - type: web
    name: gestock
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: gestock-db
          property: connectionString

databases:
  - name: gestock-db
    databaseName: gestock
    user: gestock_user 